import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/lib/providers/Providers";

import { Roboto } from "next/font/google";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "400", "500", "700", "900"],
  preload: false, // Disable preloading
  variable: "--roboto-font",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`max-w-[1680px] w-full mx-auto ${roboto.className} antialiased `}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
